#pragma once

#define FLX_RENDERER_D3D12_VALUE 0
#define FLX_RENDERER_VULKAN_VALUE 1

#define FLX_RENDERER FLX_RENDERER_VULKAN_VALUE

#define FLX_RENDERER_VULKAN (FLX_RENDERER == FLX_RENDERER_VULKAN_VALUE)
#define FLX_RENDERER_D3D12 (FLX_RENDERER == FLX_RENDERER_D3D12_VALUE)