<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <BaseOutputPath>$(SolutionDir)InfluxEditor\Bin</BaseOutputPath>
    <BaseIntermediateOutputPath>$(SolutionDir)InfluxEditor\Int</BaseIntermediateOutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <Configurations>Debug;Release;Profile</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder\**" />
    <Page Remove="NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfluxEngineDLL\InfluxEngineDLL.vcxproj" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="xcopy /I /Y &quot;$(SolutionDir)InfluxEngineDLL\Bin\x64\$(Configuration)&quot; &quot;$(OutDir)&quot;" />
  </Target>

</Project>
