#pragma once

#define FLX_RENDERER 0

#define FLX_RENDERER_D3D12 (FLX_RENDERER == 0)
#define FLX_RENDERER_VULKAN (FLX_RENDERER == 1)

#define FLX_THREADED_RENDERING 0

#define FLX_DEBUG _DEBUG
#define FLX_GFX_DEBUG FLX_DEBUG